/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaajRouteImport } from './routes/anaaj'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuniyaadiRouteImport } from './routes/buniyaadi'
import { Route as MachineRouteImport } from './routes/machine'
import { Route as MausamRouteImport } from './routes/mausam'
import { Route as PasandidaRouteImport } from './routes/pasandida'
import { Route as PedRouteImport } from './routes/ped'
import { Route as PhoolRouteImport } from './routes/phool'
import { Route as SabziRouteImport } from './routes/sabzi'
import { Route as SamparkRouteImport } from './routes/sampark'
import { Route as SrotRouteImport } from './routes/srot'
import { Route as YojanaRouteImport } from './routes/yojana'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaajRoute = AnaajRouteImport.update({
  id: '/anaaj',
  path: '/anaaj',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuniyaadiRoute = BuniyaadiRouteImport.update({
  id: '/buniyaadi',
  path: '/buniyaadi',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineRoute = MachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => rootRouteImport,
} as any)
const MausamRoute = MausamRouteImport.update({
  id: '/mausam',
  path: '/mausam',
  getParentRoute: () => rootRouteImport,
} as any)
const PasandidaRoute = PasandidaRouteImport.update({
  id: '/pasandida',
  path: '/pasandida',
  getParentRoute: () => rootRouteImport,
} as any)
const PedRoute = PedRouteImport.update({
  id: '/ped',
  path: '/ped',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoolRoute = PhoolRouteImport.update({
  id: '/phool',
  path: '/phool',
  getParentRoute: () => rootRouteImport,
} as any)
const SabziRoute = SabziRouteImport.update({
  id: '/sabzi',
  path: '/sabzi',
  getParentRoute: () => rootRouteImport,
} as any)
const SamparkRoute = SamparkRouteImport.update({
  id: '/sampark',
  path: '/sampark',
  getParentRoute: () => rootRouteImport,
} as any)
const SrotRoute = SrotRouteImport.update({
  id: '/srot',
  path: '/srot',
  getParentRoute: () => rootRouteImport,
} as any)
const YojanaRoute = YojanaRouteImport.update({
  id: '/yojana',
  path: '/yojana',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anaaj': typeof AnaajRoute
  '/auth': typeof AuthRoute
  '/buniyaadi': typeof BuniyaadiRoute
  '/machine': typeof MachineRoute
  '/mausam': typeof MausamRoute
  '/pasandida': typeof PasandidaRoute
  '/ped': typeof PedRoute
  '/phool': typeof PhoolRoute
  '/sabzi': typeof SabziRoute
  '/sampark': typeof SamparkRoute
  '/srot': typeof SrotRoute
  '/yojana': typeof YojanaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anaaj': typeof AnaajRoute
  '/auth': typeof AuthRoute
  '/buniyaadi': typeof BuniyaadiRoute
  '/machine': typeof MachineRoute
  '/mausam': typeof MausamRoute
  '/pasandida': typeof PasandidaRoute
  '/ped': typeof PedRoute
  '/phool': typeof PhoolRoute
  '/sabzi': typeof SabziRoute
  '/sampark': typeof SamparkRoute
  '/srot': typeof SrotRoute
  '/yojana': typeof YojanaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anaaj': typeof AnaajRoute
  '/auth': typeof AuthRoute
  '/buniyaadi': typeof BuniyaadiRoute
  '/machine': typeof MachineRoute
  '/mausam': typeof MausamRoute
  '/pasandida': typeof PasandidaRoute
  '/ped': typeof PedRoute
  '/phool': typeof PhoolRoute
  '/sabzi': typeof SabziRoute
  '/sampark': typeof SamparkRoute
  '/srot': typeof SrotRoute
  '/yojana': typeof YojanaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anaaj'
    | '/auth'
    | '/buniyaadi'
    | '/machine'
    | '/mausam'
    | '/pasandida'
    | '/ped'
    | '/phool'
    | '/sabzi'
    | '/sampark'
    | '/srot'
    | '/yojana'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anaaj'
    | '/auth'
    | '/buniyaadi'
    | '/machine'
    | '/mausam'
    | '/pasandida'
    | '/ped'
    | '/phool'
    | '/sabzi'
    | '/sampark'
    | '/srot'
    | '/yojana'
  id:
    | '__root__'
    | '/'
    | '/anaaj'
    | '/auth'
    | '/buniyaadi'
    | '/machine'
    | '/mausam'
    | '/pasandida'
    | '/ped'
    | '/phool'
    | '/sabzi'
    | '/sampark'
    | '/srot'
    | '/yojana'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaajRoute: typeof AnaajRoute
  AuthRoute: typeof AuthRoute
  BuniyaadiRoute: typeof BuniyaadiRoute
  MachineRoute: typeof MachineRoute
  MausamRoute: typeof MausamRoute
  PasandidaRoute: typeof PasandidaRoute
  PedRoute: typeof PedRoute
  PhoolRoute: typeof PhoolRoute
  SabziRoute: typeof SabziRoute
  SamparkRoute: typeof SamparkRoute
  SrotRoute: typeof SrotRoute
  YojanaRoute: typeof YojanaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anaaj': {
      id: '/anaaj'
      path: '/anaaj'
      fullPath: '/anaaj'
      preLoaderRoute: typeof AnaajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buniyaadi': {
      id: '/buniyaadi'
      path: '/buniyaadi'
      fullPath: '/buniyaadi'
      preLoaderRoute: typeof BuniyaadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine': {
      id: '/machine'
      path: '/machine'
      fullPath: '/machine'
      preLoaderRoute: typeof MachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mausam': {
      id: '/mausam'
      path: '/mausam'
      fullPath: '/mausam'
      preLoaderRoute: typeof MausamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasandida': {
      id: '/pasandida'
      path: '/pasandida'
      fullPath: '/pasandida'
      preLoaderRoute: typeof PasandidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ped': {
      id: '/ped'
      path: '/ped'
      fullPath: '/ped'
      preLoaderRoute: typeof PedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phool': {
      id: '/phool'
      path: '/phool'
      fullPath: '/phool'
      preLoaderRoute: typeof PhoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabzi': {
      id: '/sabzi'
      path: '/sabzi'
      fullPath: '/sabzi'
      preLoaderRoute: typeof SabziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sampark': {
      id: '/sampark'
      path: '/sampark'
      fullPath: '/sampark'
      preLoaderRoute: typeof SamparkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srot': {
      id: '/srot'
      path: '/srot'
      fullPath: '/srot'
      preLoaderRoute: typeof SrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yojana': {
      id: '/yojana'
      path: '/yojana'
      fullPath: '/yojana'
      preLoaderRoute: typeof YojanaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaajRoute: AnaajRoute,
  AuthRoute: AuthRoute,
  BuniyaadiRoute: BuniyaadiRoute,
  MachineRoute: MachineRoute,
  MausamRoute: MausamRoute,
  PasandidaRoute: PasandidaRoute,
  PedRoute: PedRoute,
  PhoolRoute: PhoolRoute,
  SabziRoute: SabziRoute,
  SamparkRoute: SamparkRoute,
  SrotRoute: SrotRoute,
  YojanaRoute: YojanaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
